version: "3.8"

services:
  client:
    stdin_open: true
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - "/client:/app/node_modules"
    - "/usr/src/app/node_modules"
    - "/usr/src/app/.next"
